######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 4 16:38:10 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += communicate.h
SOURCES += communicate.cpp main.cpp
