######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 2 13:06:31 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.C
